# Generated by Django 4.2.4 on 2023-08-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(default='SOME STRING', max_length=100),
        ),
    ]
